### ISSUE TITLE
flatten boundary data structure

### ISSUE THREAD

**Issue by hobbeshunter** [inowas/ModFlowTool#1]
```
"boundaries": {
    "WEL": [
      {
        "id": "4c8f6490-f933-4a0e-a0d8-15cecf920d61",
        "name": "H07_6",
        "date_created": "2016-11-29T20:52:16+0000",
        "date_modified": "2016-11-29T20:52:16+0000",
        "type": "WEL",
...
```

should become
```
"boundaries":  [
  {
    "id": "4c8f6490-f933-4a0e-a0d8-15cecf920d61",
    "name": "H07_6",
    "date_created": "2016-11-29T20:52:16+0000",
    "date_modified": "2016-11-29T20:52:16+0000",
    "type": "WEL",
...
```

**Comment by rabbl** [comment]
The boundaries are more easy to generate with you approach.
My idea was the following:

As we have a boundaryObject with (at the moment) 5 properties 

- chd
- ghb
- rch
- riv
- wel

we can build 5 separate properties windows and inject model.boundaries.{type}.
Also its possible to inject all boundaries and filter in the properties window.

I don't know whats more clever.

**Comment by hobbeshunter** [comment]
I think filtering is quite easy. Doing `this.state.model.boundaries..find(b => b.type == 'WEL')` wont hurt.

But we need functions that listen to changes on input tags, like that
```
  updateWellName(id, newName) {
    this.state.model.boundaries.WEL.find(b => b.id == id).name = newName;
    this.forceUpdate();
  }
```

If we flaten the data structure we can generalize easilie, like so
```
  updateBoundaryName(id, newName) {
    this.state.model.boundaries.find(b => b.id == id).name = newName;
    this.forceUpdate();
  }
```

**Comment by rabbl** [comment]
I have updated the branches ralf and dev

**Comment by hobbeshunter** [comment]
Just to avoid some confusion, you have to use `find` if you want to find one element (eg by id) and `filter` if you want to filter by another property.
